###
Send Request
GET http://localhost:3001/api/books

###
Send Request
GET http://localhost:3001/api/books/1

###
Send Request   
POST http://localhost:3001/api/books
Content-Type: application/json

{
    "tittle": "New Book",
    "author": "New Author",
}

###
Send Request
DELETE http://localhost:3001/api/books/4